services:
  app:
    build:
      target: development
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true

  horizon:
    build:
      target: development
